//
//  ConfigViewController.m
//  CouchDemo
//
//  Created by Jens Alfke on 8/8/11.
//  Copyright 2011 Couchbase, Inc. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  except in compliance with the License. You may obtain a copy of the License at
//    http://www.apache.org/licenses/LICENSE-2.0
//  Unless required by applicable law or agreed to in writing, software distributed under the
//  License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
//  either express or implied. See the License for the specific language governing permissions
//  and limitations under the License.

#import "DemoAppDelegate.h"
#import "ConfigViewController.h"
#import <Syncpoint/Syncpoint.h>
#import <Security/SecRandom.h>

// This symbol comes from GrocerySync_vers.c, generated by the versioning system.
extern double GrocerySyncVersionNumber;


@implementation ConfigViewController


@synthesize sessionInfo, sessionLabel, delegate;


- (id)init {
    self = [super initWithNibName: @"ConfigViewController" bundle: nil];
    if (self) {
        // Custom initialization
        self.navigationItem.title = @"Configure Sync";

        UIBarButtonItem* purgeButton = [[UIBarButtonItem alloc] initWithTitle: @"Done"
                                                                style:UIBarButtonItemStyleDone
                                                               target: self 
                                                               action: @selector(done:)];
        self.navigationItem.leftBarButtonItem = purgeButton;
    }
    return self;
}


#pragma mark - View lifecycle


- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    delegate = (DemoAppDelegate *)[[UIApplication sharedApplication] delegate];
    SyncpointClient* syncpoint = delegate.syncpoint;
    
    if (syncpoint.session.isPaired) {
        // we are paired, display user-id
        self.sessionInfo.text = @"Your Syncpoint User Id:";
        self.sessionLabel.text = syncpoint.session.owner_id;
    } else if (syncpoint.session.isReadyToPair) {
        // we are pairing, nothing to do but wait
        self.sessionInfo.text = @"Show this code to your administrator";
        self.sessionLabel.text = [syncpoint.session getValueOfProperty: @"pairing_token"];
    } else {
//       if facebook is around
//          activate facebook button
//          activate console button
//       else
//          act like console button was clicked
    }
}
    
// triggered by console button push
- (void) pairViaConsole {
//    set view to pairing-info style
    NSString* randomToken = [NSString stringWithFormat:@"%d", arc4random()];
    // All authentication passes through this API. For Facebook auth you'd pass
    // the oauth access token as handed back by the Facebook Connect API, like this:
    // [syncpoint pairSessionWithType:@"facebook" andToken:myFacebookAccessToken];
    // for the default console auth, you pass any random string for the token.
    
    [delegate.syncpoint pairSessionWithType:@"console" andToken:randomToken]; // todo handle error
    
    self.sessionInfo.text = @"Show this code to your administrator";
    self.sessionLabel.text = [delegate.syncpoint.session getValueOfProperty: @"pairing_token"];
}

//facebook button was clicked
- (void) pairViaFacebook {
    if (![delegate.facebook isSessionValid]) {
        [delegate.facebook authorize:nil];
        [self pop];
    }
}


- (void)pop {
    
    UINavigationController* navController = (UINavigationController*)self.parentViewController;
    [navController popViewControllerAnimated: YES];
}


- (IBAction)done:(id)sender {
    [self pop];
}


- (void)alertView:(UIAlertView *)alertView didDismissWithButtonIndex:(NSInteger)buttonIndex {
    if (buttonIndex > 0) {
        [self pop]; // Go back to the main screen without saving the URL
    }
}


@end
